# Generated by Django 5.1 on 2025-04-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_total',
        ),
    ]
