# Generated by Django 4.2.23 on 2025-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='archivee',
            field=models.BooleanField(default=False),
        ),
    ]
